### ISSUE TITLE
figure5: add panels with scores for simulated assemblies

### ISSUE THREAD

**Issue by Blahah** [Blahah/transrate-paper#10]
We are already comparing assemblies from sequencing data to the genomes of the sequenced species. However, we need to demonstrate that it's possible to get high scores with really good assemblies, and the genome comparison is not proving useful for discerning how accurate the score is.

We should perform two kinds of simulation:

1. starting with the high-confidence reference transcripts for each species, simulate reads perfectly covering the entire transcriptome. Then evaluate the reference transcripts using the simulated reads. The score should be high
2. take the simulated reads from the previous step and assemble them with various assemblers and settings. Evaluate the assemblies usign transrate and by aligning the contigs to the original reference transcripts using blat. Plot the contig scores against their blat scores, and plot transrate score vs overall blat alignment quality

**Comment by blahah** [comment]
- [x] rice
- [x] mouse
- [x] yeast
- [x] human
